name: Update Submodules

on:
  workflow_dispatch:  # allow manual trigger
  push:
    branches:
      - main  
  schedule:
    - cron: "0 0 * * *"  # daily update

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive  # update all submodules

    - name: Update submodules to latest commit
      run: |
        git submodule update --remote --merge
        git add .
        git commit -m "Update submodules to latest"
        git push origin main